AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lab Data Analytics.

  '
Globals:
  Function:
    MemorySize: 512
    Runtime: python3.6
    Timeout: 180
Parameters:
  StudentLabDataBucket:
    Type: String
Resources:
  AthenaNamedQueryStudentKeyboardStream:
    DependsOn: TableEvents
    Properties:
      Database:
        Ref: DatabaseLabMonitor
      Description:
        Fn::Sub: ${AWS::StackName} Student Keyboard Stream
      Name:
        Fn::Sub: ${AWS::StackName} Student Keyboard Stream
      QueryString:
        Fn::Sub: 'SELECT distinct(id), array_agg(key)  FROM "studentevents${AWS::StackName}"."event_stream"  WHERE
          name=''KeyPressEvent''  GROUP BY id;

          '
    Type: AWS::Athena::NamedQuery
  DatabaseLabMonitor:
    Properties:
      CatalogId:
        Ref: AWS::AccountId
      DatabaseInput:
        Description: Lab Monitor Database
        Name:
          Fn::Sub: lab_monitor_${AWS::StackName}
    Type: AWS::Glue::Database
  TableEvents:
    DependsOn: DatabaseLabMonitor
    Properties:
      CatalogId:
        Ref: AWS::AccountId
      DatabaseName:
        Ref: DatabaseLabMonitor
      TableInput:
        Description: Event from students.
        Name: event_stream
        Parameters:
          classification: json
        PartitionKeys:
        - Name: year
          Type: int
        - Name: month
          Type: int
        - Name: day
          Type: int
        - Name: hour
          Type: int
        - Name: id
          Type: string
        StorageDescriptor:
          Columns:
          - Name: x
            Type: int
          - Name: y
            Type: int
          - Name: dx
            Type: int
          - Name: dy
            Type: int
          - Name: time
            Type: timestamp
          - Name: button
            Type: string
          - Name: pressed
            Type: string
          - Name: key
            Type: string
          - Name: name
            Type: string
          - Name: ip
            Type: string
          - Name: student
            Type: string
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location:
            Fn::Sub: s3://${StudentLabDataBucket}/event_stream
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          SerdeInfo:
            Parameters:
              paths: button,dx,dy,ip,key,name,pressed,student,time,x,y
            SerializationLibrary: org.openx.data.jsonserde.JsonSerDe
        TableType: EXTERNAL_TABLE
    Type: AWS::Glue::Table
  TableProcesses:
    DependsOn: DatabaseLabMonitor
    Properties:
      CatalogId:
        Ref: AWS::AccountId
      DatabaseName:
        Ref: DatabaseLabMonitor
      TableInput:
        Description: process from students.
        Name: process_stream
        Parameters:
          classification: json
        PartitionKeys:
        - Name: year
          Type: int
        - Name: month
          Type: int
        - Name: day
          Type: int
        - Name: hour
          Type: int
        - Name: id
          Type: string
        StorageDescriptor:
          Columns:
          - Name: name
            Type: string
          - Name: pid
            Type: string
          - Name: time
            Type: string
          - Name: is_killed
            Type: boolean
          - Name: ip
            Type: string
          - Name: student
            Type: string
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location:
            Fn::Sub: s3://${StudentLabDataBucket}/process_stream
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          SerdeInfo:
            Parameters:
              paths: ip,is_killed,name,pid,student,time
            SerializationLibrary: org.openx.data.jsonserde.JsonSerDe
        TableType: EXTERNAL_TABLE
    Type: AWS::Glue::Table
Transform: AWS::Serverless-2016-10-31
